### ISSUE TITLE
Leave command

### ISSUE THREAD

**Issue by vadmurzakov** [vadmurzakov/telegram-bot-search-goodboy#9]
Реализовать логику /leave команды

**Comment by vadmurzakov** [comment]
```
2023-02-03T13:47:55.441Z ERROR 1 --- [elegram.org/...] bot.service.business.BotService          : Неизвестная ошибка: 

java.lang.NullPointerException: Cannot invoke "bot.service.providers.CommandProvider.execute(com.pengrad.telegrambot.model.Message)" because the return value of "java.util.Map.get(Object)" is null
        at bot.service.business.BotService.lambda$listener$0(BotService.java:44) ~[classes!/:2.1.1]
        at com.pengrad.telegrambot.impl.UpdatesHandler$1.onResponse(UpdatesHandler.java:73) ~[java-telegram-bot-api-6.3.0.jar!/:na]
        at com.pengrad.telegrambot.impl.UpdatesHandler$1.onResponse(UpdatesHandler.java:49) ~[java-telegram-bot-api-6.3.0.jar!/:na]
        at com.pengrad.telegrambot.impl.TelegramBotClient$1.onResponse(TelegramBotClient.java:53) ~[java-telegram-bot-api-6.3.0.jar!/:na]
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519) ~[okhttp-4.10.0.jar!/:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:831) ~[na:na]
```
